### PR TITLE
Changes on the Java gui application

### PR DESCRIPTION
**Pull request by joelsnape**
I was trying the Java application on my linux machine and found some issues and a minor improvement that I corrected in my branch. Copying the commit messages the changes addressed are the follwing:
    - Correction of a problem with the login process that prevented the login after one failed atempt. Added an option to the User and ModelUser getKey methods allowing the caller to force the generation of the key.
    - Correction of a problem in linux (Kubuntu) and OpenJDK 7 (7u71-2.5.3-0ubuntu0.14.04.1): The "Enter for copy" doesn't copy the password to the clipboard. Maybe there is a better way to fix the problem but the only way I found was to wait one second between the "Enter" action an the System.exit command.
    - It bothered me that the password was shown (and in big letters) every time the application is used so I added a checkbox (default "on") to mask most of the password (the application shows the first and last characters of the password).

### CODE REVIEW

**Comment by lhunath** [comment]
Good catch on the missing super call.  WRT the application not closing, it closes fine on OS X, which is why I didn't notice.  I don't have a Linux box around at this time with an X server to test it on.  I'll see if I can figure it out.  I don't like adding time-dependant hacks.

— Maarten Billemont (lhunath) —
me: http://www.lhunath.com <http://www.lhunath.com/> – business: http://www.lyndir.com <http://www.lyndir.com/> – http://masterpasswordapp.com <http://masterpasswordapp.com/>

**Comment by joelsnape** [comment]
Ok, since your machine doesn't have the problem, I tried to find the problem by trial and error and I think I found it... I think the problem it's in com.lyndir.masterpassword.gui.Res, the ExecutorService is created and used but never released (by shutdown() for example, as indicated in the documentation "An unused ExecutorService should be shut down to allow reclamation of its resources."). 
In my machine, it's enough to make a failed login attempt for the executor to be used (in UnlockFrame.trySignIn) and after that the application fails to close gracefully (on the UnlockFrame the setDefaultCloseOperation is called with WindowConstants.DISPOSE_ON_CLOSE). I tried to add a shutdown method just to test my hypothesis and it worked but, since the Res class is used in many places, the ExecutorService can't be shutdown in just any place.

**Comment by lhunath** [comment]
Give master a try again?

— Maarten Billemont (lhunath) —
me: http://www.lhunath.com <http://www.lhunath.com/> – business: http://www.lyndir.com <http://www.lyndir.com/> – http://masterpasswordapp.com <http://masterpasswordapp.com/>

**Comment by joelsnape** [comment]
I tried the new version and pressing enter now closes the window, however, the password is still not copied, using the close button of the UnlockFrame window only terminates the application before trying to log in and the PasswordFrame still uses the less gracefull EXIT_ON_CLOSE way to close. I think the better solution is to use DISPOSE_ON_CLOSE on the default close operation of all the windows and dispose the PasswordFrame when pressing enter finding a way to shutdown the the ExecutorService of the com.lyndir.masterpassword.gui.Res class when the application is closed (maybe changing the Res class from a singleton to a disposable component that is disposed with the window where it's instantiated?).
The failed password problem still occurs since the super.reset() was still not added on the ModelUser.reset().

**Comment by lhunath** [comment]
Getting close now, but for some reason the application stays up when closing the PasswordFrame still.  The executor services have all been shut down AFAIK.

**Comment by joelsnape** [comment]
Well, I don't know exactly why but in my machine the windowClosing listener is only called once (for the last closed frame I imagine) and so only one of the executors is released... I tried with windowClosed and that will work perfectly on my machine (each window will call the listener once and the password is copied when that functionality is used) just don't forget to call setDefaultCloseOperation with WindowConstants.DISPOSE_ON_CLOSE on the PasswordFrame (in GUI and AppleGUI).

**Comment by lhunath** [comment]
Looks like DISPOSE_ON_CLOSE isn't the default as I assumed.  Also, windowClosing is actually just a request to close the window using the default close operation, which is a very unfortunate name for the thing.  It doesn't get triggered at all for a non-interactive close operation.  So as you suggested, I'm now using windowClosed.

**Pull request closed without merging**
