### PR TITLE
Added option -p to suppress identicon

### PR DESCRIPTION
**Pull request by damko**
I'm not sure if this little enhancement goes in line with your roadmap/plans but I needed to use MasterPassword in a pipeline so I added the -p parameter to remove the identicon from the output.

### CODE REVIEW

**Comment by ilpianista** [comment]
Oh I just saw this, sorry!

I implemented the same in #176, but using the already existing `-q` parameter.

+1 to implement something like this however.

**Comment by damko** [comment]
haha almost exactly the same code at the same time. I'm glad to have this new feature in master. Thanks

**Comment by damko** [comment]
oh I just noticed that none of our PR is yet in master

**Comment by lhunath** [comment]
This is no longer relevant; the identicon is already hidden with -q in the master CLI.

**Pull request closed without merging**
