### PR TITLE
Fix #129 No more missing symbols from o in x class

### LINKED ISSUE #129: MP-12 Missing symbols from o in x character class.
https://project.lyndir.com/youtrack/issue/MP-12

For some reason, the x character class doesn't include all of the o class' symbols.  I'm unsure why this is, but if there's no clear reason, we should probably consider fixing this by realigning the sets.  This would be a compatibility breaking change so it would have to be postponed to an algorithm version change that affects all generated passwords (eg. a scrypt parameter bump).

### PR DESCRIPTION
**Pull request by mylainos**
Because of breaking changes the new version is now v4.
The scrypt parameter MP_N have been changed so new passwords will be different.
I will add tests, modify the other versions (other than C) and change the documentation.

### CODE REVIEW

**Comment by Mylainos** [comment]
How have you create the results in MasterPassword/C/mpw_tests.xml?

**Comment by lhunath** [comment]
Thank you for the contribution.  I've been holding off on fixing this due to the algorithm incompatibility.  I'll probably postpone this until the algorithm needs a bump for more pressing reasons, such as an update to the scrypt parameters.

**Comment by lhunath** [comment]
The `MasterPassword/C/mpw_tests.xml` file was written manually after testing the algorithm's output across architectures and different code implementations (Java / C / JS / ObjC, the latter no longer exists).

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.

**Pull request closed without merging**
