### PR TITLE
Webpack build

### PR DESCRIPTION
**Pull request by jedevc**
This PR adds a number of features that should aid in future development and production builds.

- npm packages. Dependencies are contained in a package.json and are easier to install and update. This contrasts from the previous approach where the dependencies were directly checked into git.
- webpack. The use of a modern build system specifically catered for compiling javascript allows easy inclusion of dependencies, polyfills and use of next-generation javascript. It also has the potential to easily add CSS processing libraries such as LESS or SASS in the future if desired. It also allows for easier development through the `npm run start:dev` command which watches files for changes and recompiles the source code.

I've moved a few files around in this request, but nothing that breaks compatibility. The only major change for hosting this is that the build results are placed in the `web-js/dist/` folder as opposed to directly in the `web-js/` folder. Note that while git claims a lot has changed, most of those changes are simply a result of removing the dependencies directly from git and adding the `package-lock.json` file.

Hope this helps out with improving the web interface and opens the way for more flexible development in the future.

### CODE REVIEW

**Comment by lhunath** [comment]
All of this looks great from first glance; I do want to add to the conversation that the motivation for making dependencies explicit as opposed to managed through a repo was the security concerns of fetching executable code from external parties.  I don't know how npm works, how well vetted and how secure its repositories & transfers are.  But these concerns should probably be a part of this conversation.

**Comment by jedevc** [comment]
The way that I understand it, NPM is simply a place for package owners to place their packages. What the build process does is download the packages from npm and build them into the bundles. At no point in time will a user load any scripts from any other location than the server that hosts the master password app.

Downloading a package from NPM is similar to downloading the library from the site of the package owner manually, however, it allows updates and such more easily. Certain parts of npm are a little dodgier than others, however, note that the only dependencies that are built into the bundles are babel-polyfill and jquery, two very widely trusted packages. In my opinion the risk of using npm to download dependencies over having explicit files is very low. In fact it may even be reduced by allowing easier security updates which could prevent user data from being stolen through a potential vulnerability.

Hope that clears things up a bit?

**Comment by lhunath** [comment]
It doesn't investigate the risk introduced.  Who maintains `npm`, who maintains the packages, how far do access privileges to those packages extend, what would be necessary for an attacker to inject code into a package or hijack the dependency resolution process, in what way does `npm` guarantee me that the code it's downloading for me is genuine, and what conditions would be required to break that guarantee?

The website will not load packages off npm, I realize, but it is the expectation that the user should be able to check out this repo and run the code in it.  I'm not a huge fan of imposing upon the user the need for them to extend their trust beyond me into an opaque process of dependency resolution.

**Comment by mario-d-s** [comment]
> NPM is simply a place for package owners to place their packages.

I'd like to clarify here that `npm` itself is a CLI package manager for javascript, open sourced at https://github.com/npm/npm and distributed as part of [NodeJS](https://nodejs.org/en/).

There is also https://npmjs.org, the public registry owned by the company NPM, Inc., which the tool `npm` uses by default to fetch packages from.

If you are **really** this paranoid about security, there is the possibility to still use `npm` the tool, but configure another registry that is entirely in your control. I have no idea, however, how much work that takes. I can only imagine it is "a lot".

I'd be surprised if you're *really* this unfamiliar with NPM, but just in case I'll point out the obvious: *thousands* of projects rely on NPM to manage dependencies, and if there would be any serious security issues, pretty much the entire world would be in trouble, not only this app or your webpage.

They have their own [security policy](https://www.npmjs.com/policies/security), I'd suggest you read it and see what specific concerns you have after doing that.

@jedevc would it be possible to just use WebPack and benefit from a full-fledged build framework, without involving NPM at all?

**Comment by mario-d-s** [comment]
It seems you aren't the only one with concerns w.r.t. package security. Here's an interesting blog post I just found: https://medium.com/redpoint/introducing-pkgsign-package-signing-and-verification-for-npm-5b833e0ec2d4

So, `pkgsign` is something to look into, although it's a very young solution.

**Comment by jedevc** [comment]
Also to add:

Hijacking packages and such has been done in the past, mostly through a technique known as typo-squatting. This technique is when a package adopts a similar name to a well known package and injects potentially malicious code. However, npm has methods for resolving this (see [here](https://www.npmjs.com/policies/disputes)) when notified by users. To verify that the package, npm downloads the packages over https.

It can still be dangerous to install npm packages without being completely sure of the repercussions as noted by various events in the past few years. It is important to note from these issues, that most of the problems stem from the fact that many people install npm packages without thinking about the possibility of malicious code being included. By keeping the number of packages installed to a well-supported and widely trusted few, this risk can be mitigated.

If a library lists an npm package in its documentation, then to download that package from npm is just as risky as downloading it from their website directly. For example, you already trust jquery by including the minified version from their website, so why not trust a package that they have published on npm?

One final thing about reproducability of builds. If you look at the `package-lock.json` file, it contains a list of every single package installed. By including these, it allows anyone to easily reproduce the exact build that I have on my computer now.

If you are really not ok with including npm packages in the build, then those can be removed and replaced with the old manual dependencies, however, as I've said before, without proper updates and regular manual intervention could lead to a potential security hole in the application. Or alternatively, as mentioned, could use something like `pkgsign` or even a different package manager such as `yarn` which is developed by facebook and is said to have better security (although it still uses npmjs.com).

**Comment by lhunath** [comment]
I'm very well aware of npm, its use-case and its popularity, but by no means does that by itself count for anything in terms of guarantees.  It's not because the world uses a thing, that the thing is definitely secure enough for a password manager.  Furthermore, please be conscious of the fact that whatever decisions are made here effectively impose upon all users the level of trust that we deem acceptable.  Authority or popularity is not a valuable measure of trustworthiness.

**Comment by lhunath** [comment]
I'm primarily interested in investigation and gathering knowledge, identifying the weaknesses and addressing them if deemed necessary.

A possibility would be to keep in the repo a hash that can be used to verify whether a downloaded package is identical to a package that has been checked and verified by us prior.

**Comment by jedevc** [comment]
Just found something that might be interesting at the documentation for the `package-lock.json` file [here](https://docs.npmjs.com/files/package-lock.json#integrity). 

Essentially, for each package listed, there is an integrity property which contains a SHA of the package. This appears to be a [Standard Subresource Integrity](https://w3c.github.io/webappsec-subresource-integrity/). The installed package will be checked against this value to ensure nothing has gone wrong (either accidentally or maliciously). So what this means is that the end user can install the same set of packages that you select to install.

**Comment by mario-d-s** [comment]
@lhunath I just wanted to say I really appreciate your pragmatism here and your high standards for security. I'm actively relying on your app for all my password needs so it's good to see you employ these practices.

**Comment by jedevc** [comment]
Yeah, definitely agree with @mario-d-s here. I use this tool a lot as well, and recommend it my friends. Having seen your high standards in action now, I feel a lot more confident in my use of it and in persuading other people to give it a try as well.

**Comment by rolandog** [comment]
As a user, I'm a stakeholder with an interest on MPW's robustness and security. I'm usually a spectator, but I'd like to step-in and contribute my two cents on this matter.

I find myself agreeing with @lhunath's healthy skepticism, after all there have been cases where repositories holding open-source packages have been hacked before [1], or where the system of trust in the npm ecosystem itself was vulnerable [2]. Also there was the `left-pad` incident [3] that inspired two research papers, one published in September 2017 [4] that lists their contributions as:

> [...] (i) we quantitatively study the phenomena of micro-packages and their impact in a software ecosystem,  (ii)  we  motivate  the  need  to  revisit  best  practices to increase software resilience to  their ecosystem changes and (iii) we motivate the need for developers to be aware of how sensitive  their  third-party  dependencies  are  to  changes  in  a software ecosystem

The other research paper [5] is still ongoing, and is about software ecosystem health, but also .

> [...] From a more technical point of view, typical examples of health problems are packages containing bugs or security vulnerabilities, causing potential problems in packages depending on it. The impact of the problem grows as the number of transitive dependencies on a problematic package grows.

From the perspective of risk mitigation, just to be on the safe side, we'd need to map our dependencies and our dependencies' dependencies and so on, and then determine or quantify their trustworthiness, and how to increase it (or, conversely, lower the risk of a vulnerability/bug skipping past us). This should be put and explained in the documentation, so that users understand that they would be using a product that has a larger attack surface.

However, I'm all for increasing documentation, code readability, and code re-usability within the project. And I can't but be thankful that @jedevc has been kind enough to dedicate his expertise and time to refactor and improve having productivity in mind.

MPW will continue, IMHO, to appeal to its userbase as long as it is a robust, secure and stateless method of generating passwords.

Perhaps there is a way of having it both ways: having 'version pinned' npm packages and having some sort of fixed development cycle or stable/testing branches. What are your thoughts @lhunath ? 

References
[1] https://github.com/JabRef/jabref/issues/1670
[2] http://blog.npmjs.org/post/141702881055/package-install-scripts-vulnerability
[3] http://blog.npmjs.org/post/141577284765/kik-left-pad-and-npm
[4] https://arxiv.org/pdf/1709.04638.pdf
[5] https://arxiv.org/pdf/1711.04532.pdf

**Comment by jedevc** [comment]
> From the perspective of risk mitigation, just to be on the safe side, we'd need to map our dependencies and our dependencies' dependencies and so on, and then determine or quantify their trustworthiness, and how to increase it (or, conversely, lower the risk of a vulnerability/bug skipping past us). This should be put and explained in the documentation, so that users understand that they would be using a product that has a larger attack surface.

@rolandog can you clarify what you mean by "map our dependencies"? Would this be simply checking a package hash, checking a digital signature (I'm not sure how many packages are digitally signed though...) or something more complex?

Also thanks for bringing up those papers; events in the past have questioned the effectiveness of the system. I think it's worth mentioning that many large projects have taken these criticisms to heart and are working on improving transparency and ensuring that the number of dependencies is kept to a safe minimum

> This should be put and explained in the documentation, so that users understand that they would be using a product that has a larger attack surface.

If we do go through with using npm, then I definitely think that we should do this.

Additionally, I've found [snyk](https://snyk.io), and other similar tools which allow for monitoring a code base for vulnerabilities in dependencies. If the npm route is decided on, maybe using a tool like this could help improve security.

**Comment by lhunath** [comment]
Project has moved to https://gitlab.com/MasterPassword due to GitHub ownership change.  This issue has been migrated, feel free to follow the conversation there.

**Pull request closed without merging**
